CREATE TABLE IF NOT EXISTS channels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channelName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channelId INTEGER NOT NULL UNIQUE,
    normalTicket INTEGER NOT NULL DEFAULT 0,
    preferentialTicket INTEGER NOT NULL DEFAULT 0,
    voiceRate REAL NOT NULL DEFAULT 1.4,
    voicePitch REAL NOT NULL DEFAULT 0.9,
    selectedVoiceURI TEXT DEFAULT 'mute',
    toneDuration INTEGER NOT NULL DEFAULT 500,
    toneSequence TEXT NOT NULL DEFAULT '[]',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (channelId) REFERENCES channels(id) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS update_app_state_timestamp
AFTER UPDATE ON app_state
BEGIN
    UPDATE app_state SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

CREATE TABLE IF NOT EXISTS ticket_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channelId INTEGER NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('N', 'P')),
    ticket INTEGER NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (channelId) REFERENCES channels(id) ON DELETE CASCADE
);
